### PR TITLE
Update pl_PL.lang

### PR DESCRIPTION
**Pull request by Radk6**
Fixed a few typos I missed when I first translated the mod and changed the Dynamic Lights tooltip a bit since its' quality options cannot be translated (yet?). Also updated NotFine translation.

### CODE REVIEW

**Review by Pxx500 — APPROVED** [review]
looks good

**Comment by mitchej123** [comment]
Can you rebase on master?  Seems there's some line ending differences.

**Comment by Radk6** [comment]
> Can you rebase on master? Seems there's some line ending differences.

Will do once I get back home

**Comment by mitchej123** [comment]
Will merge once rebased

**Comment by Dream-Master** [comment]
@Pxx500 @Radk6

**Comment by Pxx500** [comment]
I already approved, Mitch merges for angelica

**Comment by Dream-Master** [comment]
yes but conflicts need to be resolved

**Comment by Radk6** [comment]
> Will merge once rebased

Should be fine now

**Pull request merged**
