### PR TITLE
Show tooltiops for shader options

### PR DESCRIPTION
**Pull request by TotallyNotOndre**
image
fix https://github.com/GTNewHorizons/Angelica/issues/690

### CODE REVIEW

**Comment by Cleptomania** [comment]
For some reason I can't capture a screenshot of these tooltips, but the tooltip positioning seems to go from the bottom of the screen. If you turn GUI scale down to like 2 or 3 it's apparent. That problem isn't really a problem with this PR, but it would be nice to fix that at the same time if possible?

**Comment by TotallyNotOndre** [comment]
should i just draw it at mouse location?

**Comment by Cleptomania** [comment]
I toyed with it, and changing
```
final int y = this.height - (panelHeight + 4);
```
to
```
int y = mouseY + 10;
if (y + panelheight >= (this.height - 4)) y = this.height - (panelHeight + 4);
```

This looks much better in my opinion, but I checked modern Iris and it actually still always draws the tooltip at the bottom too. So not sure what we should do there. Personally I like the Y level being based on the mouse position.

**Comment by TotallyNotOndre** [comment]
looks more readable than if it just follows the cursor

**Comment by Cleptomania** [comment]
I think we can just merge this as is, it's in line with what Iris is doing in modern, if we wanna change the positioning later we can revisit it

**Review by Cleptomania — APPROVED** [review]

**Comment by TotallyNotOndre** [comment]
ok then

**Pull request merged**
