### PR TITLE
Preliminary ChunkAPI/EndlessIDs compatibility

### PR DESCRIPTION
**Pull request by FalsePattern**
This is a minimal viable compatibility patch for ChunkAPI (and thus EndlessIDs).

Note: This might also require other changes to work properly, it needs to be tested in a larger instance to make sure things don't break horribly when the extended IDs start being used. I don't know much about Angelica's codebase so this is the only required change i could spot.

Related issue: #29

### CODE REVIEW

**Comment by Caedis** [comment]
Have you been able to test it with EndlessIDs directly in-game?

**Comment by Cleptomania** [comment]
I tested with EndlessIDs in game and I get the following error resulting in a crash:

```
java.lang.UnsupportedOperationException: A mod that is incompatible with EndlessIDs has tried to access the biome array of a chunk like in vanilla! Crashing in fear of potential world corruption!
```

I assume this is coming from the below line, but I'm not sure what the proper way is to handle this with ChunkAPI/EndlessIDs. https://github.com/FalsePattern/Angelica/blob/5e8ef6156fd47da693c8642bf4d97f63d59503f0/src/main/java/me/jellysquid/mods/sodium/client/world/cloned/ClonedChunkSection.java#L61

I have tested these changes with ChunkAPI/EndlessIDs not included and it doesn't cause any issue when they aren't present.

**Comment by Cleptomania** [comment]
I added one change for the `hasSky` setting, there appears to be some condition where `ExtendedBlockStorage.skylightArrray` can be null while the `chunk.worldObj.provider.hasNoSky` doesn't line up with that. I'm not exactly certain why those conditions don't line up though.

With that change Angelica appears to be fully functional with EndlessIDs from my testing in game though. If we're happy with the changes code-wise I'd say it's good to merge probably.

**Comment by Caedis** [comment]
After this is merged, i'll move all of the mod checks to a Compat class so they are not all in the main mod.

**Comment by Caedis** [comment]
@FalsePattern any input on what was recently commited?

**Comment by FalsePattern** [comment]
The skylight array nullness not lining up with the hasNoSky field is a bit odd but it probably won't cause any problems after the fix in https://github.com/GTNewHorizons/Angelica/pull/94/commits/112fe7ace99590985ef9e81f006447bfb9195401, and ChunkAPI's copy logic also handles this mismatch gracefully by writing null to the target ExtendedBlockStorage.
Relevant methods in case someone wants to verify this:
- cAPI skylight array copy: https://github.com/FalsePattern/ChunkAPI/blob/588a14ce93aec49df10d24b89c70bc245e1526ad/src/main/java/com/falsepattern/chunk/internal/vanilla/SkylightManager.java#L67
- cAPI array copy helper: https://github.com/FalsePattern/ChunkAPI/blob/588a14ce93aec49df10d24b89c70bc245e1526ad/src/main/java/com/falsepattern/chunk/api/ArrayUtil.java#L144

**Review by Caedis — APPROVED** [review]

**Comment by Caedis** [comment]
@mitchej123 feel free to take a final look over and merge it

**Pull request merged**
