### PR TITLE
Hud caching angelica

### PR DESCRIPTION
**Pull request by Cardinalstars**
Potential fix for HudCaching, don't know if there is going to be issues with this though.

### CODE REVIEW

**Comment by Caedis** [comment]
Looks good, tested in game and full pack and the enchantments looks fine now

**Comment by Cardinalstars** [comment]
> Looks good, tested in game and full pack and the enchantments looks fine now

Solid, I will work on removing those redundant openGL calls now.

**Comment by Caedis** [comment]
@Alexdoru can you work your ASM magic here?

**Comment by Cardinalstars** [comment]
I honestly don't know exactly why, but the last GL11.glEnable after the tesselator.
GL11.glEnable(GL11.GL_ALPHA_TEST);
Won't go away even though my ASM clearly shows it being removed while stepping through it.

**Comment by Alexdoru** [comment]
don't merge it yet, I want to change some stuff

**Comment by Alexdoru** [comment]
when holding an enchanted item, it changes the color of the crosshair 
image

**Review by Alexdoru — CHANGES_REQUESTED** [review]
can you fix the crosshair color

**Comment by Alexdoru** [comment]
> I honestly don't know exactly why, but the last GL11.glEnable after the tesselator. GL11.glEnable(GL11.GL_ALPHA_TEST); Won't go away even though my ASM clearly shows it being removed while stepping through it. My class dump could be wrong ¯\_(ツ)_/¯

this is what your thing does 
image

**Comment by mitchej123** [comment]
What's the status on this?

**Comment by Alexdoru** [comment]
Idk, am I supposed to point out things that don't work or am I supposed to fix it ? I'd try not removing the last ColorMask call

**Comment by Alexdoru** [comment]
I tried not removing the colorMask thing and only removing the tessellator calls and that's not it

**Comment by mitchej123** [comment]
Going to merge as is, can always forward fix

**Pull request merged**
