### PR TITLE
Fix campfire backport animations

### PR DESCRIPTION
**Pull request by makamys**
This PR fixes Campfire Backport's animations not playing when `speedupAnimations` is enabled. It does this by doing two things:
- It adds a hook to `RenderBlocks#drawCrossedSquares` to mark animated icons.
  - Fixes campfire flames, as well as [this test pack](https://github.com/GTNewHorizons/Hodgepodge/files/12908735/animated_crossed_squares_pack.zip)'s poppies not animating.
- It adds hooks to [`RenderBlockCampfire`](https://github.com/connor135246/Campfire-Backport/blob/951901efc6b9f5585dc2d354d3582ab2e84fe7b8/src/main/java/connor135246/campfirebackport/client/rendering/RenderBlockCampfire.java)'s face rendering methods to mark animated icons. It would be a good idea to add an API for this later, but since there is currently none, patching them from Angelica's side is necessary.
  - Fixes campfire embers and the mixed campfires in the NEI handlers not animating.

### CODE REVIEW

**Comment by mitchej123** [comment]
Hmm, failed with 
```
/home/runner/work/Angelica/Angelica/src/main/java/com/gtnewhorizons/angelica/mixins/late/client/campfirebackport/MixinRenderBlockCampfire.java:17: error: Mixin target connor135246.campfirebackport.client.rendering.RenderBlockCampfire could not be found
@Mixin(targets = "connor135246.campfirebackport.client.rendering.RenderBlockCampfire")
```

**Comment by makamys** [comment]
Oops, I guess I have to add Campfire Backport as a compile time dependency.

**Comment by mitchej123** [comment]
kinda surprised my jabba mixin doesn't need it; unless something else is pulling it in as a dep...

**Comment by makamys** [comment]
Jabba *is* already a dep:
https://github.com/GTNewHorizons/Angelica/blob/0d79f5e19377b56b1668e41498e8d794bff1c632/dependencies.gradle#L87

**Comment by mitchej123** [comment]
🤦

**Comment by makamys** [comment]
There we go, this time I actually tested it in production 😅

**Pull request merged**
